### ISSUE TITLE
Add Map Object in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#102]
Create a new file named mapObject in JavaScript_Advance and add the following:

- Where we use mapObject in .md
- How we make mapObject in .md
- Example of mapObject in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by adavijit** [comment]
@Swap76  I want to go with it

**Comment by Swap76** [comment]
@adavijit Go Ahead with it :-)

**Comment by adavijit** [comment]
@Swap76 done! sorry again for two PRs.

**Comment by Swap76** [comment]
@Tamy123 Sorry from my side it is becoming difficult to manage 

@Tamy123 you can do one thing can add content into the files created by @adavijit

**Comment by Tamy123** [comment]
Its okay i ll just look for another one of yours?
