### ISSUE TITLE
Add DOM Manipulation using JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#103]
Create a new file named domManipulation in Javascript_Basics and add the following:

- Where we use domManipulation in .md
- How we make domManipulation in .md
- Example of domManipulation in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by Andras-Simon** [comment]
@Swap76 Can I work on this one?

**Comment by Swap76** [comment]
Hey @Andras-Simon ,

Assigned the issue to you
