### ISSUE TITLE
Add Concat function 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#107]
Create a new file named concat() in JavaScript_Advance and add the following:

- Where we use concat()  in .md
- How we make concat()  in .md
- Example of concat()  in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by TorstenDittmann** [comment]
I can take care of that :)

**Comment by Swap76** [comment]
@TorstenDittmann sorry but this issue is created after the request of @adavijit 

You can also suggest to me what we can add more so that we can work on that

**Comment by TorstenDittmann** [comment]
Ah no problem. I could do something about polymorphism.

**Comment by Swap76** [comment]
@TorstenDittmann Great I have created #112 for you comment there so that I can assign you to it

**Comment by adavijit** [comment]
@Swap76  I want to go with this
