### ISSUE TITLE
Add Comparison operators in JavaScript 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#108]
Create a new file named comparisonOprators in JavaScript_Basic and add the following:

- Where we use comparisonOprators in .md
- How we make comparisonOprators in .md
- Example of comparisonOprators in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by Tamy123** [comment]
What about this one?

**Comment by Swap76** [comment]
@Tamy123 Assigning to you :-)

**Comment by Omkaragrawal** [comment]
Hey I would like to take this up

**Comment by Swap76** [comment]
@Omkaragrawal Please make sure you are adding different examples and all than @Tamy123
