### ISSUE TITLE
Add continue and break in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#109]
Create a new file named continue-break in JavaScript_Basic and add the following:

- Where we use continue-break in .md
- How we make continue-break in .md
- Example of continue-break in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by paullaffitte** [comment]
Hello, could I work on this?

**Comment by Swap76** [comment]
@paullaffitte Sure. Assigning to you :-)
