### ISSUE TITLE
Add about JSON in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#111]
Create a new file named json in JavaScript_Advance and add the following:

- Where we use JSON in .md
- How we access and manipulate  JSON in .md
- Example of JSON in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by Rudy-Menekam** [comment]
hello, can i work on this?

**Comment by Swap76** [comment]
@Rudy-Menekam sure just make sure you do all things that are mentioned there and you shouldn’t  just copy-paste

Happy Contributing :-)
