### ISSUE TITLE
Add Different types of assignments in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#115]
Create a new file named assignments in JavaScript_Advance and add the following:

- Different types of assignments in .md
<img width="934" alt="Screenshot 2019-10-17 at 1 56 16 PM" src="https://user-images.githubusercontent.com/37082605/66991845-6f2ee780-f0e6-11e9-84a9-3898d5b1540a.png">

- Example of assignments in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by phyyyl** [comment]
I'll do it

**Comment by phyyyl** [comment]
PR #124
