### ISSUE TITLE
Add Number Methods in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#116]
Create a new file named numberMethods in JavaScript_Basics and add the following:

- How we can use and manipulate using the numerical methods in .md
- Example of numerical methods in .js
<img width="936" alt="Screenshot 2019-10-17 at 2 03 55 PM" src="https://user-images.githubusercontent.com/37082605/66992161-fc723c00-f0e6-11e9-8eb7-cc354e8436cc.png">

Create .md and .js both files as we are shifting to Docsify

**Comment by dvlprdave** [comment]
I would love to work on this. Could you assign me is possible? Thank you.

**Comment by Swap76** [comment]
@dvlprdave Have you sent the PR for it

**Comment by dvlprdave** [comment]
Not yet. Will send a PR tomorrow for sure. Currently working on a bunch of stuff.

**Comment by Swap76** [comment]
@dvlprdave Cool

**Comment by dvlprdave** [comment]
Just sent the PR.
