### ISSUE TITLE
Add Number Properties in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#118]
Create a new file named numberProperties in JavaScript_Basics and add the following:

- How we can use the numerical properties in .md
- Example of numerical properties in .js

<img width="935" alt="Screenshot 2019-10-17 at 2 05 27 PM" src="https://user-images.githubusercontent.com/37082605/66992298-33485200-f0e7-11e9-82ea-e4b033e811ab.png">

Create .md and .js both files as we are shifting to Docsify

**Comment by GiacomoPignoni** [comment]
I will take this

**Comment by Swap76** [comment]
@GiacomoPignoni Assigned to you :-)

**Comment by Swap76** [comment]
@GiacomoPignoni Have you sent the PR for the issue
