### ISSUE TITLE
Suggest JavaScript concepts and add it that are not there

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#127]
This is a common issue where anyone can tell me about the concepts or examples they want to add.

After that

- I will be creating a separate issue for that to keep track of the work
- Will assign to the person
- Start Contributing :-)

Thanks to all for making this project so big :-)

**Comment by antoav** [comment]
Hi, I would like to add the concept of while and do while loops. I did a quick search and wasn't able to find that there, so I believe those concepts haven't been worked on yet :)

**Comment by Swap76** [comment]
@antoav I have created #132 for you comment their so that I can assign it to you

**Comment by sealedHuman** [comment]
I couldn't find if other array functions (namely the *some*, *every*, *find*, *map*, and *reduce* functions) are currently covered in the examples/docs. Are those covered already? If not, I'd love to add them.

**Comment by Swap76** [comment]
@sealedHuman Those methods are already covered. If you know any other concept then also let me know

**Comment by sealedHuman** [comment]
Oh I missed those, but see them now. Thanks.
