### ISSUE TITLE
Add Connection to Redis

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#130]
Add configuration for Redis 

- Add how-to connect with Redis.

- Where can we get the free Redis instant

- Basic Redis operations

Add the .js file in JavaScript_Advance and also create .md file explaining all this in docs/JavaScript_Advance

**Comment by Rudy-Menekam** [comment]
hello, want to work on this

**Comment by Swap76** [comment]
@Rudy-Menekam start contributing I have assigned the issue to you

**Comment by Rudy-Menekam** [comment]
ok @Swap76
