### ISSUE TITLE
Add While and Do-While loops in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#132]
Create a new file named while and do-while in JavaScript_Advance and add the following:

**Create separate file for both as it will be good to maintain it** 

- Where we use those loops in .md
- Example using those loops in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by jisack** [comment]
i can take a look at this .

**Comment by Swap76** [comment]
@jisack sorry but this issue is created on request of @antoav if she does not comment here in 2 days then you can take 

Also if you can add something to the project let me know will create the issue for you :-)

**Comment by cos1715** [comment]
what do you need?

**Comment by M0706** [comment]
Can you explain your issue with more clarity ?

**Comment by Swap76** [comment]
@cos1715 @M0706  sorry but this issue is created on request of @antoav if she does not comment here in 2 days then you can take

Also if you can add something to the project let me know will create the issue for you :-)

**Comment by antoav** [comment]
Hi, thanks for creating my request. I'll work on it :)

**Comment by jisack** [comment]
@Swap76 ok, i just done yesterday but never mind .

**Comment by Swap76** [comment]
@jisack Thanks for the info, I'm thinking of merging 2-3 PRs for this as the examples and use cases can be very wide
