### ISSUE TITLE
Generate the _sidebar.md file from the list of files in docs

### ISSUE THREAD

**Issue by paullaffitte** [Swap76/Learn-JavaScript#136]
It could be nice if the `_sidebar.md` file would be generated from the list of files in the docs directory. It will allow to always keep it up to date. Moreover an `npm run serve-docs` would be appreciable.

If you think that it's a good idea, I would like to work on it.

**Comment by Swap76** [comment]
@paullaffitte Great Idea go ahead with it :-)
