### ISSUE TITLE
Add array functions related to sorting and math 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#139]
Use an existing file named array-methods in JavaScript_Basics and add the following:

- Sorting an Array
- Reversing an Array
- Math.min
- Math.max

Create .md and .js both files as we are shifting to Docsify

**Comment by sneha122** [comment]
hey I would like to work on this

**Comment by Swap76** [comment]
@Swap76 You can start working on it :-)

**Comment by Omkaragrawal** [comment]
I too would like to take this up.

**Comment by Swap76** [comment]
@Omkaragrawal Go ahead with it I will merge good things from you both
