### ISSUE TITLE
Add Methods related to array

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#140]
Use an existing file named array-methods in JavaScript_Basics and add the following:

- Array.every()
- Array.reduceRight()
- Array.some()
- Array.lastIndexOf()

Create .md and .js both files as we are shifting to Docsify

**Comment by kirii009** [comment]
Hey Swapnil, I would like to work on it

**Comment by Swap76** [comment]
@kirii009 go ahead with it :-)

**Comment by Omkaragrawal** [comment]
I too would like to do it.

**Comment by Swap76** [comment]
@Omkaragrawal I think for this a PR is already merged only a small amount of work is left.

Let me know if you have something to add to in repo
