### ISSUE TITLE
Add Math functions in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#141]
Create file named math in JavaScript_Basics and add the following:

- Math.round()
- Math.pow()
- Math.sqrt()
- Math.abs()

In .md file you have to explain how math can be used its syntax

Create .md and .js both files as we are shifting to Docsify

**Comment by sneha122** [comment]
Hey I would like to work on this

**Comment by Swap76** [comment]
@sneha122 go ahead and start working :-)

**Comment by Leannelb** [comment]
Hi, can I work on this too please?

**Comment by Swap76** [comment]
@sneha122 Is working on it you both can work I think I will merge the best from both
