### ISSUE TITLE
Add Math functions in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#142]
Create new file named math in JavaScript_Basics and add the following:

- Math.ceil()
- Math.floor()
- Math.sin()
- Math.cos()
- Math.min() and Math.max()
- Math.random()

In .md file you have to explain how math can be used its syntax

Create .md and .js both files as we are shifting to Docsify

**Comment by Abhishek-Mittall** [comment]
I will take this . Please assign me this

**Comment by sneha122** [comment]
Can i take this issue?

**Comment by Swap76** [comment]
@sneha122 @Abhishek-Mittall You both can work on this at last  I will merge both of your PRs after seeing what is better in which PR

**Comment by Abhishek-Mittall** [comment]
okay

**Comment by thekazi** [comment]
Can I work on this?

**Comment by Swap76** [comment]
@thekazi 3 people on the same issue will be very problematic maybe you 3 can talk and divide the work or enhance upon each others work

**Comment by Abhishek-Mittall** [comment]
I have already send you pull request.Please have a look at it.
