### ISSUE TITLE
Add DOM Manipulation of CSS and Animation using JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#143]
A created a new file named Dom-manipulation  in JavaScript_Advance and add the following:

- CSS Manipulation 
- Animation manipulation
- DOM Events

Create .md and .js both files as we are shifting to Docsify

**Comment by sneha122** [comment]
I would like to work on this

**Comment by Swap76** [comment]
@sneha122 Sorry but you have already assigned 2 Issues you can complete those at that time you can contribute to other issues 
Thanks :-)

**Comment by Leannelb** [comment]
Hi I'd like to give this one a go please? If that's alright please.

**Comment by Swap76** [comment]
@Leannelb Go ahead with it :-)
