### ISSUE TITLE
Add DOM Manipulation properties 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#145]
A created a new file named Dom-manipulation-html in JavaScript_Advance and add the following:

- DOM Navigation
- Working with DOM Nodes
- Working with DOM Collections

Create .md and .js both files as we are shifting to Docsify

**Comment by Swap76** [comment]
@RobinTHOREL For the issue, you have to create two files 

1. in Dom-manipulation-html.js which will have examples with comments of the respective topic
2. in Dom-manipulation-html.md in this, there should have to be info about these methods how we 

can use it where we can use it and how it will help our websites, etc.

**Comment by sprakash57** [comment]
Raised PR #168 for this issue. Please review and let me know if anything needs any improvement.
