### ISSUE TITLE
Add about Browser Object Model in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#146]
Add browser-object-model.md in . Javascript_Advance which will have

- What we can do using BOM Model
- Why to use it 
- How we can optimize our sites after taking inputs

**Comment by Rudy-Menekam** [comment]
hello, can I work on this?

**Comment by Swap76** [comment]
@Rudy-Menekam Go ahead with it

**Comment by Swap76** [comment]
@Rudy-Menekam Have you made a PR for it

**Comment by Rudy-Menekam** [comment]
I just made a pull request @Swap76 and sorry for the late submission

**Comment by Rudy-Menekam** [comment]
and I don't know if I got the third point right.
