### ISSUE TITLE
Add info about AJAX 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#149]
Add info about AJAX in simple language for this create a file named AJAX.md in docs/JavaScript_Advance which will be a Markdown file

Add the following things:

- What is AJAX
- How AJAX works

**Comment by lancedingo** [comment]
on it

**Comment by Swap76** [comment]
@lancedingo please see to it that 2 PRs #150 and #163 has been merged so you add something different than that
