### ISSUE TITLE
Add about XMLHttpRequest Object

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#151]
A created a new file named XMLhttpRequest in JavaScript_Advance and add the following:

<img width="952" alt="Screenshot 2019-10-19 at 3 10 17 PM" src="https://user-images.githubusercontent.com/37082605/67142829-9a4e3e00-f282-11e9-90d1-79ddc60c3c67.png">

Create .md and .js both files as we are shifting to Docsify

**Comment by jisack** [comment]
@Swap76 i would like to take this instead haha .

**Comment by Swap76** [comment]
@jisack Cool please make sure you right things in your words and with examples

**Comment by jisack** [comment]
@Swap76 could this been closed now or i should write the markdown file

**Comment by Swap76** [comment]
@Swap76 You can make a separate pull request for it :-)
