### ISSUE TITLE
Add sending a request to a server using AJAX 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#152]
A created a new file named AJAXrequest in JavaScript_Advance and add the following:

<img width="952" alt="Screenshot 2019-10-19 at 3 12 16 PM" src="https://user-images.githubusercontent.com/37082605/67142854-ff099880-f282-11e9-9327-57021eb4be8e.png">

Create .md and .js both files as we are shifting to Docsify

**Comment by eLeontev** [comment]
I will take care

**Comment by BhaveshSalunke** [comment]
Is it all core or xhr request would work?

**Comment by BhaveshSalunke** [comment]
Like is it a wrapper for xhr?

**Comment by Swap76** [comment]
@BhaveshSalunke It should be a example in .js file how to do it and in .md file the info should be there

**Comment by Swap76** [comment]
@BhaveshSalunke You can work on GET method as @eLeontev Has added post method and also you can work on adding info in .md file
