### ISSUE TITLE
Add ESlint into project and add the command for linting and fixing

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#16]
**Add ESlint into the project with following rules**
- 2 space tab allowed
- line break of only one line allowed in code
- No line breaks at the end of file
- ES6 syntax
- single quotes only
- semicolon always

also, add .eslintignore
which will exclude node_modules and *.json file and any other if needed

If you are working on the issue let me know through the comment will assign the issue to you then

**Comment by MarineP31** [comment]
I'll like to help you !

**Comment by pavitra14** [comment]
I'm Working on this :)

**Comment by Swap76** [comment]
Hey guys,

It's ok if you both work on this as @pavitra14 you haven't mentioned your presence before @MarineP31. 

Best PR amongst you both will be Merged

**Comment by pavitra14** [comment]
Can you please elaborate the 2nd point if it's not too much trouble :)
"line break only one code"

**Comment by Swap76** [comment]
Hey @pavitra14,

Updated the description sorry for the inconvenience from my side
