### ISSUE TITLE
Deploy the documentation to github page

### ISSUE THREAD

**Issue by paullaffitte** [Swap76/Learn-JavaScript#183]
Docsify can be deployed to github page as mentioned [here](https://docsify.js.org/#/deploy?id=github-pages). It could be nice to do so to be able to access the docs without cloning the repository.
- [ ] The sidebar should be generated before each commit with a githook, maybe using husky, to be sure that it is always up to date.
- [ ] The lint command should be run before each commit with a hook too, to be sure that the new content respect the current norm.

**Comment by Swap76** [comment]
@paullaffitte Good Idea 

Husky for linting is dangerous for us as it is example doc there will be many unused variables and in such cases  husky should let us commit the code

**Comment by paullaffitte** [comment]
@Swap76 Right, I didn't think about it before. Maybe I should check the PR #178 that I did yesterday with the auto-fix using the linter, I'm afraid that it induced some mistakes like removing some unused variables. But it's a pity to have a linter and not being able to use it, maybe it should be configured to only yield warning instead of errors in some case or even ignore some files?

**Comment by Swap76** [comment]
@paullaffitte I think we have to revisit the whole as I am now seeing let changed to const 

If you are free please have a look we can divide the work I will be seeing all the files in JavaScript basics you can take JavaScript advance as in advance there will not be much work just see to it that because of const some methods will stop working and will emit errors

**Comment by Swap76** [comment]
@paullaffitte I have reverted all the const to let whichever place necessary

**Comment by paullaffitte** [comment]
@Swap76 I'll work on advance part as soon as I can

**Comment by Swap76** [comment]
@paullaffitte I have done it also one person has helped me doing it

**Comment by paullaffitte** [comment]
Is the documentation now available online? I just read the readme and didn't find any link about it.

**Comment by Swap76** [comment]
@paullaffitte I have made changes & deployed on GitHub pages now only. 
link:- swap76.github.io/learn-javascript/
