### ISSUE TITLE
Add info about Classes in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#186]
Add the info in classes.md placed in docs/JavaScriptBasics 

Use the example given in JavaScript_Basics for explaining Classes

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by jcespinosa** [comment]
I would like on this :)
Please assign this issue to me

**Comment by Swap76** [comment]
@jcespinosa Assigned to you

**Comment by Swap76** [comment]
@jcespinosa you are working on it right

**Comment by jcespinosa** [comment]
Yes! I'm making the last changes ;)

**Comment by Swap76** [comment]
@jcespinosa Cool

**Comment by nishant-sethi** [comment]
@Swap76 is it open. Can I take this up?

**Comment by Swap76** [comment]
@nishant-sethi Yes you can add more questions or answers to existing questions

If adding answers it should be seen after clicking a drop-down button named solutions
