### ISSUE TITLE
Add info about Higher Order functions in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#187]
Add the info in higher_order_functions.md placed in docs/JavaScriptBasics

Use the example given in JavaScript_Basics for explaining Higher Order functions

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by anuk79** [comment]
@Swap76 Can I pick this issue?

**Comment by Swap76** [comment]
@anuk79 Go ahead with it :-)

**Comment by anuk79** [comment]
Thanks 💃

**Comment by anuk79** [comment]
@Swap76 - the pr -  https://github.com/Swap76/Learn-JavaScript/pull/239

**Comment by Swap76** [comment]
@anuk79 Please do the needed changes said in PR

**Comment by anuk79** [comment]
@Swap76 done changes, please review
