### ISSUE TITLE
Add info about if, if else ladder and other Conditional Statements in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#188]
Add the info in conditional_statments.md placed in docs/JavaScriptBasics

Use the example given in JavaScript_Basics for explaining Conditional Statements

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by lnchapin** [comment]
Hey, conditional_statements.md doesn't exist at the moment but I'll take this one and make it.

**Comment by lnchapin** [comment]
Hey, I'll take this one

**Comment by NiyongaboEric** [comment]
Can I also try it ?

**Comment by Swap76** [comment]
@NiyongaboEric @lnchapin You both can take this I will merge the best things together
