### ISSUE TITLE
Add info about Inheritance in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#189]
Add the info in inheritance.md placed in docs/JavaScriptBasics

Use the example given in JavaScript_Basics for explaining inheritance

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by mpaarating** [comment]
I can take this @Swap76

**Comment by Swap76** [comment]
@mpaarating Go ahead with it
