### ISSUE TITLE
Add Async Await Example info

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#19]
Create a new file named async-await in JavaScript_Advanced and add the following:

- Why use async-await (Code before and after async-await)

- More info if there and make a request to open API with async-await

If anyone is taking the issue please comment to save efforts of others

**Comment by rishabhnehra** [comment]
Would like to contribute to this

**Comment by Swap76** [comment]
@rishabhnehra You can start working on it will assign it to you

**Comment by Swap76** [comment]
@rishabhnehra  Create .md file as we are shifting to docsify

**Comment by rishabhnehra** [comment]
Sure @Swap76
