### ISSUE TITLE
Add info about Splice & Slice in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#194]
Add the info in splice_slice.md placed in docs/JavaScriptBasics

Use the example given in JavaScript_Basics for explaining Splice & Slice

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by Surya97** [comment]
Is this issue still open? Can I work on this?

**Comment by Swap76** [comment]
@Surya97 you can start working on it
