### ISSUE TITLE
Add info about Variables in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#197]
Add the info in variables.md placed in docs/JavaScriptBasics

Use the example given in JavaScript_Basics for explaining Variables

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by harshit2000** [comment]
This variable returns the value from the server

**Comment by Swap76** [comment]
@harshit2000 Didn’t get you can you elaborate on that
