### ISSUE TITLE
Add info about Arrow functions in JavaScipt

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#199]
Add the info in arrow_function.md placed in docs/JavaScriptAdvance

Use the example given in JavaScript_Advance for explaining Arrow functions

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by eswong610** [comment]
Hi, can I work on this for hacktoberfest?

**Comment by Swap76** [comment]
@eswong610 Yes go ahead with it
