### ISSUE TITLE
Add info about Async & Await in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#200]
Add the info in async_await.md placed in docs/JavaScriptAdvance

Use the example given in JavaScript_Advance for explaining Async & Await

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by johachi** [comment]
I'm doing this now!

**Comment by Swap76** [comment]
@johachi Go-ahead with it

**Comment by Swap76** [comment]
@johachi you are working on it right

**Comment by johachi** [comment]
Yes! You will see a PR soon.

**Comment by Swap76** [comment]
@johachi Cool take you time

**Comment by johachi** [comment]
@Swap76 I'm done. Will check my spelling tomorrow, and then send you a PR.

**Comment by Swap76** [comment]
@johachi Cool super excited for it :-)
