### ISSUE TITLE
Add info about Default Values in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#201]
Add the info in default_values.md placed in docs/JavaScriptAdvance

Use the example given in JavaScript_Advance for explaining Default Values

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by WojciechPreficz** [comment]
I can do that. :)

**Comment by Swap76** [comment]
@WojciechPreficz Go ahead with the issue
