### ISSUE TITLE
Add info about Destructuring in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#203]
Add the info in destructuring.md placed in docs/JavaScriptAdvance

Use the example given in JavaScript_Advance for explaining Destructuring

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by HurricaneInteractive** [comment]
I will add some more info around this topic 👍

**Comment by NiyongaboEric** [comment]
@Swap76 Let me give a try

**Comment by NiyongaboEric** [comment]
@Swap76 I would like to work on it

**Comment by Swap76** [comment]
@NiyongaboEric Go ahead with it
