### ISSUE TITLE
Add info about using Express in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#205]
Add the info in express.md placed in docs/JavaScriptAdvance

Use the example given in JavaScript_Advance for explaining Express

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by NiyongaboEric** [comment]
@Swap76 I worked on it, here is my [PR](https://github.com/Swap76/Learn-JavaScript/pull/232/files)
