### ISSUE TITLE
Add info about FS Module in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#206]
Add the info in fs_module.md placed in docs/JavaScriptAdvance

Use the example given in JavaScript_Advance for explaining FS Module

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by frahmadani** [comment]
Hi @Swap76, I'd like to try working on this

**Comment by frahmadani** [comment]
Hi, I've submitted PR #223, hope it's acceptable
