### ISSUE TITLE
Add info about Prototypes in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#207]
Add the info in prototypes.md placed in docs/JavaScriptAdvance

Use the example given in JavaScript_Advance for explaining Prototypes

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by dnafication** [comment]
Hi @Swap76, Can I take this? I have written the content. Will send the PR.

**Comment by Swap76** [comment]
@dnafication Cool
