### ISSUE TITLE
Add info about Spread & Rest Operators

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#208]
Add the info in spread_&_rest.md placed in docs/JavaScriptAdvance

Use the example given in JavaScript_Advance for explaining Spread & Rest Operators

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by sealedHuman** [comment]
I'm working on this.

**Comment by sealedHuman** [comment]
PR #219 created for this.

**Comment by Swap76** [comment]
@sealedHuman Checked It was perfect
