### ISSUE TITLE
Add info about Timer Functions in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#209]
Add the info in timer_function.md placed in docs/JavaScriptAdvance

Use the example given in JavaScript_Advance for explaining Timer functions

You can also explain with more examples taking reference is ok but directly copying is not allowed

**Comment by shahpranaf** [comment]
Hi @Swap76 ,
I would like to work on it. Kindly assign it to me.

Thanks

**Comment by Swap76** [comment]
@shahpranaf Assigned to you
