### ISSUE TITLE
Add callback example with info

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#21]
Create a new file named callback in JavaScript_Advanced and add the following:

Where callbacks are used 

Also, discuss the problem of callback hell

More info if there and make a request to open API with callbacks

Create .md file as we are shifting to docsify

Have a .js file which can be executed separately and .md also

If anyone is taking the issue please comment to save efforts of others

**Comment by Swap76** [comment]
Create .md file as we are shifting to docsify

**Comment by n1rna** [comment]
I would like to take this one :)

**Comment by Swap76** [comment]
Great will assign it to you :-)

Please follow the instructions if you have a better idea of implementing it please let me know.

**Comment by n1rna** [comment]
hey @Swap76 , I was wondering if you think it is a good idea to talk a little about closures in js, before using them and calling API endpoints?
I will try to keep it short and to the point.

**Comment by Swap76** [comment]
@n1rna Great Idea go ahead with it :-)
