### ISSUE TITLE
Add Basic JavaScript Questions 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#210]
Add Basic JavaScript questions in docs/exercise/JavaScript_Basic

This questions should help others to test their skills

For contents in JavaScript_Basic you can check all the topics from docs/JavaScript_Basics

**Comment by samisafatli** [comment]
Hello, I'm gonna tackle this one, is it closed already?
If not, should I insert the questions inside the Exercise-1.md?

**Comment by arthursvpb** [comment]
Did it.  #216

**Comment by arthursvpb** [comment]
Resolves #216

**Comment by arthursvpb** [comment]
Did it. #216
