### ISSUE TITLE
Add promise chaining example with info

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#22]
Create a new file named promise-chaining in JavaScript_Advanced and add the following:

Where we use promise-chaining

More info if there and make a request to open API with promise chaining

If anyone is taking the issue please comment to save efforts of others

Create .md file as we are shifting to docsify

**Comment by NeboCode** [comment]
I want to do this one 👍

**Comment by NeboCode** [comment]
Sure!

**Comment by Swap76** [comment]
@NeboCode have a .js file which can be executed separately and .md also

**Comment by NeboCode** [comment]
Will do 👍

**Comment by jamesaspence** [comment]
I can take this ticket. Please assign to me.

**Comment by Swap76** [comment]
@jamesaspence Assigned a small request will while writing JS use ES6

**Comment by jamesaspence** [comment]
This is done @Swap76 if you'd like to close this issue
