### ISSUE TITLE
Building the sidebar from docs directories content Failing

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#222]
The script for building the sidebar is written in scripts/build_sidebar.js

But the sidebar creation is failing with error
<img width="804" alt="Screenshot 2019-10-26 at 12 13 36 PM" src="https://user-images.githubusercontent.com/37082605/67615488-cae62880-f7ea-11e9-93a5-f9067a6ad654.png">

**Comment by shahpranaf** [comment]
check the node version. Install latest version 13.0.1. With older version of node this will not work.

**Comment by Swap76** [comment]
@shahpranaf Thanks for help will try :-)
