### ISSUE TITLE
Add Map & Set example and info in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#23]
Create a new file named map&set in JavaScript_Advanced and add the following:

How to use map&set

What is the use of map&set

Discuss about Weakmap & Weakset

If anyone is taking the issue please comment to save efforts of others

**Comment by Swap76** [comment]
Create .md file as we are shifting to docsify

**Comment by cyh0968** [comment]
Okay, then I will try this!

**Comment by Swap76** [comment]
@cyh0968 Start working on it will assign you to the issue
