### ISSUE TITLE
Add missing concepts of JavaScript Basics

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#241]
Please have a look at the repo in the JavaScript_Basics folder if you know any concept that is missing comment here I will create a separate issue for tracking the progress of it.

Also, you can add the docs for the same concept in docs/JavaScript_Basics

**Comment by lnchapin** [comment]
I'm working on one going over the various types of loops, I saw we have one for looping over objects but have skipped over for loops, do whiles, whiles, etc.

**Comment by Swap76** [comment]
@lnchapin Go ahead with it

**Comment by nishant-sethi** [comment]
@Swap76 I can look into this one.

**Comment by Swap76** [comment]
@nishant-sethi Cool let know the missing stuff then I will create an issue for you to start working on it and for keeping track of things

**Comment by cyh0968** [comment]
There is no error-handling, I will add error handling part

**Comment by Swap76** [comment]
@cyh0968 Cool. Looking Forward to the PR :-)
