### ISSUE TITLE
Add Missing Javascript Advance Concepts 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#242]
Please have a look at the repo in the JavaScript_Advance folder if you know any concept that is missing comment here I will create a separate issue for tracking the progress of it.

Also, you can add the docs for the same concept in docs/JavaScript_Advance

**Comment by jyburns** [comment]
@Swap76 Would you consider Array.reduce() a unique advanced topic? I would love to write up an example and some documentation for it.

**Comment by jyburns** [comment]
Ah, never mind, I see it is under JS Basics already... I would be happy to add Object.keys() or Object.assign() most likely under JS Basics though.

**Comment by Swap76** [comment]
@jyburns Actually I wanted to segregate the JavaScript_Basics but due to hacktoberfest many people are contributing to the repo It ok put it in JavaScript Advance.

After some time I will segregate the files

**Comment by jyburns** [comment]
@Swap76 Sounds good 👍 i'll open up a PR for Object.keys() and another for Object.assign() if that  works.

**Comment by Swap76** [comment]
@jyburns Cool
