### ISSUE TITLE
Add Exercise Questions for Array Methods in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#243]
Add the Exercise question for Array Method in docs/Exercise/Javascript_Basics/array_method.md which can be solved using JavaScript 

The question can be open-ended or a task to complete to learn the concept

**Comment by MoisesTR** [comment]
Hi @Swap76 ,
I would like to work on it. Kindly assign it to me.

Thanks

**Comment by Swap76** [comment]
@MoisesTR Go ahead with it

**Comment by MoisesTR** [comment]
I did the pull request, please tell me if it's ok what I uploaded @Swap76

**Comment by Swap76** [comment]
@MoisesTR Sure
