### ISSUE TITLE
Add Exercise Questions for Bitwise Operators in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#244]
Add the Exercise question for Bitwise Operators in docs/Exercise/Javascript_Basics/bitwise_operator.md which can be solved using JavaScript 

The question can be open-ended or a task to complete to learn the concept

**Comment by aenkirch** [comment]
Solved this issue here : https://github.com/Swap76/Learn-JavaScript/pull/275/commits/fb0e70b59f73ef251ca2a276049caa24d9ce803d
