### ISSUE TITLE
Add Exercise Questions for Boolean in JavaScript 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#245]
Add the Exercise question for Boolean in docs/Exercise/Javascript_Basics/boolean.md which can be solved using JavaScript

The question can be open-ended or a task to complete to learn the concept

**Comment by anuk79** [comment]
@Swap76 can I work on this issue?

**Comment by Swap76** [comment]
@anuk79 Go Ahead with it

**Comment by anuk79** [comment]
raised Pr https://github.com/Swap76/Learn-JavaScript/pull/285
