### ISSUE TITLE
Add Exercise Questions for Continue & Break  in JavaScript 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#248]
Add the Exercise question for Continue & Break in docs/Exercise/Javascript_Basics/continue_break.md which can be solved using JavaScript

The question can be open-ended or a task to complete to learn the concept

**Comment by MoisesTR** [comment]
Hi @Swap76 ,
I would like to work on it. Kindly assign it to me.

Thanks
