### ISSUE TITLE
Add Exercise Questions for DOM Manipulation in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#249]
Add the Exercise question for DOM Manipulation in docs/Exercise/Javascript_Basics/dom_manipulation.md which can be solved using JavaScript

The question can be open-ended or a task to complete to learn the concept

**Comment by zEduardofaria** [comment]
I'd like to take this one!

**Comment by zEduardofaria** [comment]
Check #311
