### ISSUE TITLE
Add Exercise Questions for Filters in JavaScript 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#251]
Add the Exercise question for Filters in docs/Exercise/Javascript_Basics/filters.md which can be solved using JavaScript

The question can be open-ended or a task to complete to learn the concept

**Comment by MoisesTR** [comment]
Hi @Swap76 ,
I would like to work on it. Kindly assign it to me.

Thanks

**Comment by Ahmed-Elbessfy** [comment]
Hi @MoisesTR 
It doesn't work like that. You only need to fork the main repository then =>> clone it to your local machine =>> then make changes =>> then check for conflicts =>> then push it back and make a pull request

**Comment by Swap76** [comment]
@Ahmed-Elbessfy Very good Explanation I was thinking of making a contribution guide can you take that responsibility on you as you are very good in explaining concepts

**Comment by Ahmed-Elbessfy** [comment]
OK but we may have to discuss what rules do you want because this is my first time creating a file like this

**Comment by Swap76** [comment]
@Ahmed-Elbessfy Yes

**Comment by Ahmed-Elbessfy** [comment]
Ok let's my problem first then we will discuss this one

**Comment by Swap76** [comment]
@Ahmed-Elbessfy Cool
