### ISSUE TITLE
Add Exercise Questions for IF Else in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#254]
Add the Exercise question for If Else in docs/Exercise/Javascript_Basics/if_else.md which can be solved using JavaScript

The question can be open-ended or a task to complete to learn the concept

**Comment by garrowp** [comment]
I can take this one

**Comment by luweina** [comment]
Hi i can do this

**Comment by Swap76** [comment]
@luweina You can add the solution for the If_else Question or add the questions

**Comment by geeksesi** [comment]
hi,
where should put the solution ?

**Comment by Swap76** [comment]
@geeksesi In the same file docs/Exercise/JavaScript_Basics/if_else.md

**Comment by nishant-sethi** [comment]
@Swap76 can I take this up?

**Comment by Swap76** [comment]
@nishant-sethi Yes you can add more questions or answers to existing questions 

If adding answers it should be seen after clicking a drop-down button named solutions
