### ISSUE TITLE
Add Exercise Questions for Reduce function in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#266]
Add the Exercise question for Reduce function in docs/Exercise/Javascript_Basics/reduce_function.md which can be solved using JavaScript

The question can be open-ended or a task to complete to learn the concept

**Comment by risc12** [comment]
I'd love to create an MR for this!

**Comment by risc12** [comment]
See https://github.com/Swap76/Learn-JavaScript/pull/287
