### ISSUE TITLE
Setup Express with a route

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#27]
Setup Express for creating a server 

Create a route and controller for the route

Add .js and .md both

**Comment by andregallacci** [comment]
I will start solving this issue, how should I create the .md?

**Comment by andregallacci** [comment]
I have a problem, the issue #16  is preventing any commit from being done as it needs the entire project to conform to eslint standards.

**Comment by Swap76** [comment]
@andregallacci can you tell me steps to reproduce it as others have submitted the PR's for them its working

**Comment by Swap76** [comment]
@andregallacci Create .md in docs/JavaScript_Advance

There you can write about the express and any other things related to that 

If the answer does not satisfy your requirements please elaborate the question
