### ISSUE TITLE
Add Exercise Questions for String Operation in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#270]
Add the Exercise question for String Operation in docs/Exercise/Javascript_Basics/string_operation.md which can be solved using JavaScript

The question can be open-ended or a task to complete to learn the concept

**Comment by Ahmed-Elbessfy** [comment]
what do you mean with string operation? do you mean concatenation?

**Comment by Swap76** [comment]
@Ahmed-Elbessfy Yes Concatenation or any other thing like manipulation etc.

**Comment by Ahmed-Elbessfy** [comment]
OK I will make a tut for that

**Comment by Ahmed-Elbessfy** [comment]
check PR #331
