### ISSUE TITLE
Convert pages from .js to .md in presentable manner

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#3]
Convert pages from .js to .md in presentable manner 

Anyone can take any file for conversion but make sure you store conversions into docs and the specified file 

If you are working on any file then please comment here this will save our efforts.

**Comment by Swap76** [comment]
@piyushpriyadarshi Great store them separately .md in docs/* and .js file in main directly in JavaScriptAdvance

**Comment by er-raoniz** [comment]
@Swap76 
I would like to convert some files from `js` to `md`. Would you please help me out with the exact procedure for the same?

**Comment by Swap76** [comment]
@er-raoniz Please le tme know which files you want to convert then I will convert seprate issue to keep track of the work

The converstion has following steps:

- Add examples related to that concept in the respective folder JavaScriptBasics or JavaScriptAdvance

- If info is there like uses and benefits etc add that as .md into docs folder

**Comment by er-raoniz** [comment]
@Swap76 
Oh, I see. Only those in the *docs* folder need to be in `markdown`, the example files would be in `.js`?
Still, I guess the *Exercise-1.txt* file in the *JavaScriptBasics* folder needs to be in `markdown`?

**Comment by Swap76** [comment]
Yes only pages from docs should be markdown 

and yes the Exercise-1.txt should have to be in mardown under new Section called Exercise

@er-raoniz if you will be sorting both out great if not let me I will assign some one else for the task

**Comment by er-raoniz** [comment]
@Swap76 
I would like sorting the issue, only if you can specify where does *Exercise* section needs to be placed?

**Comment by Swap76** [comment]
@er-raoniz The Exercise Section should the main Section like JavaScriptAdvance AND basics 

The the exercise section add the Advance and Basic so that people can add the exercises in respective places

And the Question will reside in docs/Exercise/JavaScriptAdvanceOrJavaScriptBasics as .md file

and answer in the outer folder in .js

**Comment by er-raoniz** [comment]
@Swap76 
Yeah, got it! I will immediately start with that! Thanks!

**Comment by Swap76** [comment]
@er-raoniz Great Super Exited for it

**Comment by jamesaspence** [comment]
I can take the promises file as I just worked on it. Do we want the file in JS still? Or are we replacing the JS w/ the MD?

**Comment by Swap76** [comment]
@jamesaspence we want the file in js also such that users can test it and play with and
