### ISSUE TITLE
JSON Parsing and Stringify

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#30]
Request to Open API and show how to use parsing 

Where to use Stringify method

Add .js and .md both

**Comment by EddyVinck** [comment]
Hi, I could do this. 

I have a few questions:
1. By "Stringify", do you mean `JSON.stringify()`? 
2. Where should the .js and .md files go?

**Comment by Swap76** [comment]
Yes correct Stringify means I want to say JSON.stringify()

.js file should be going in the JavaScript_Advance folder which will contain code for the request to open API

.md will be in ./docs/JavaScript_Advance there you can place info like 

- when we use this 

- how to use and can reference the .js code there 

If you have any idea for taking this module ahead please let me know

**Comment by EddyVinck** [comment]
Ok, I will start working on this. If I have any ideas or suggestions I will let you know!

**Comment by Swap76** [comment]
Great :-)

**Comment by EddyVinck** [comment]
@Swap76 Can you take a look? I submitted a pull request
