### ISSUE TITLE
Adding hoistings in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#36]
Create a new file named hoistings in JavaScript_Advanced and add the following:

- Where we use hoistings in js

- More info if there about hoistings

- Create .md file as we are shifting to docsify

**Comment by Swap76** [comment]
Hey @HamidOsouli this issue is created after talks in #5 . It is already assigned to a person you can tell me a concept that you know and will love to contribute in the repo

**Comment by Omkaragrawal** [comment]
Hey @Swap76  I require some time, as I am gathering all the info as well as dealing with my unit tests in my college. I will not be able to do it this week.

**Comment by adavijit** [comment]
Hey! sent PR, please check and merge

**Comment by Swap76** [comment]
@adavijit Done

**Comment by Swap76** [comment]
@Omkaragrawal Tell me the issue on which you will like to work on or want to add content after you get free
