### ISSUE TITLE
Adding How to Filter an Array using the filter method

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#37]
Create a new file named FilteringArray in JavaScript_Advanced and add the following:

- Where we use the filter method

- More info if there about filter method 
 
- Create .md file as we are shifting to Docsify

**Comment by sliee17** [comment]
Can I work on this one?

**Comment by Venkat230407** [comment]
Can i start working on that?

**Comment by Swap76** [comment]
@Venkat230407 @liquorburn Is also working on this you can tell me what you can contribute.  I will create the issue for you with description

**Comment by Venkat230407** [comment]
I can contribute c#, javascript, anglura2 and above

**Comment by liquorburn** [comment]
Here you are: https://github.com/Swap76/Learn-JavaScript/pull/46

**Comment by Swap76** [comment]
@Venkat230407 Tell me a concept of Javascript which is not there in the repo I will create an issue for you to work on.
