### ISSUE TITLE
Adding Date, Date Format, GET,SET methods of Date

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#39]
Create the file named Date in JavaScript_Basics and add the following:

- Where we use the date

- More info about date format

- Add get set methods of date

- Create .md and .js  file as we are shifting to Docsify

**Comment by Sbabureddy** [comment]
I can work on it?

**Comment by sapsa07** [comment]
Can I work on it?

**Comment by Swap76** [comment]
@sapsa07 I am assigning this to you as @Sbabureddy is already working on #41
