### ISSUE TITLE
Add Switch Cases in Javascript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#40]
Create the file named Switch in JavaScript_Basics and add the following:

- Where we use the Switch 

- More info about Switch 

- Create .md and .js  file as we are shifting to Docsify

**Comment by sapsa07** [comment]
Lets do this

**Comment by Swap76** [comment]
Hey @maddyBoy and @sapsa07 you can both work on the same issue then I have o take best from you 2.
I will advice you can take different issues if you are unable to find what you want let me know I will Add it

**Comment by adavijit** [comment]
Hey just sent some pull request!
