### ISSUE TITLE
Add Regex example and info

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#41]
Create a new file named Regex in JavaScript_Basics and add the following:

- Where we use the Regex

- More info if there about Regex 
 
- Create .md and .js both files as we are shifting to Docsify

**Comment by Swap76** [comment]
@Sbabureddy Great I have assigned the issue to you

**Comment by einnar82** [comment]
@Swap76 can i add more?

**Comment by Swap76** [comment]
@einnar82 Yes you can.

Assigned the issue to you also
