### ISSUE TITLE
Add Mapping of arrays using map method

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#43]
Create a new file named Map in JavaScript_Basics and add the following:

- Where we use the map

- More info if there about map

- Create .md and .js both files as we are shifting to Docsify

**Comment by jatin33** [comment]
Hi,
How can I help?

**Comment by sliee17** [comment]
I will be doing this :)

**Comment by Swap76** [comment]
@sliee17 Assiging to you

**Comment by Swap76** [comment]
@jatin33  Sorry this new issue is born after conversations in #5  was discussed Because of that assigning to @sliee17
