### ISSUE TITLE
Add JavaScript page redirectes

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#58]
Create a new file named javascript-page-redirects.js in JavaScript_Basic and add the following:

- Where we use page redirects
- how we use page redirects
- Auto-refresh

Create .md and .js both files as we are shifting to Docsify

**Comment by MaruthiMohanReddyPutha** [comment]
I am going to work on this feature. I think the filename does not align with the content. It could be something like javascript-page-redirects.js or something similar. What do you think?

**Comment by Swap76** [comment]
@MaruthiMohanReddyPutha thanks for reporting it 

I was in a hurry while making it thanks :-)
