### ISSUE TITLE
Add JavaScript math functions

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#59]
Create a new file named Cookies in JavaScript_Basic and add the following:

- Where we use math
- how we use different math

Create .md and .js both files as we are shifting to Docsify

**Comment by Tamy123** [comment]
Can  i take this issue? And please provide me with more details?

**Comment by JacobMGEvans** [comment]
If no one makes a PR for this in an hour or so I will follow up with one. 
@Tamy123 sounds like to me its just a basic "tutorial" like explanation of the Math API in JavaScript
I would say borrowing some highlights from MDN documentation would be a good place to start

**Comment by jvleon** [comment]
do it !

**Comment by Swap76** [comment]
@JacobMGEvans @jvleon @Tamy123 Hey you can distribute the work among 3 as there are many functions and It will be great if we can have all this here
