### ISSUE TITLE
Add sending AJAX request from Javascript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#60]
Create a new file named AJAX in JavaScript_Advance and add the following:

- Where we use AJAX requests
- how we make AJAX requests

Create .md and .js both files as we are shifting to Docsify

**Comment by maal26** [comment]
Can I take this issue?

**Comment by Tamy123** [comment]
Can you give me more details of this issue so i can work on it?

**Comment by jvleon** [comment]
I take it !

**Comment by Swap76** [comment]
@maal26 @Tamy123 @jvleon  As you 3 are there for the same issue make ajax requests to different API's and show best practices for making a API requests 

Also, provide the documentation for the same for the begginers
