### ISSUE TITLE
Add Bitwise operators info and examples 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#70]
Add the info in .md and examples in .js file named bitwise-oprators.js

Add the following operations:

- AND
- OR
- NOT
- XOR
- Signed right shift

You can also add other operators in the project

**Comment by adavijit** [comment]
javascript advance or basic? @Swap76

**Comment by Swap76** [comment]
@adavijit put the file in basic

**Comment by adavijit** [comment]
Thanks @Swap76 ! please check my last commits too

**Comment by adavijit** [comment]
@Swap76  done! please check the last commits 
#76 
#77
