### ISSUE TITLE
Higher order functions like filter,reduce,mapForEach are not available

### ISSUE THREAD

**Issue by adavijit** [Swap76/Learn-JavaScript#80]
Higher order functions like filter,reduce,mapForEach are not available.
@Swap76 Please assign this to me. And I'll do it

**Comment by Swap76** [comment]
@adavijit Assigned to you looking forward to your PR

**Comment by adavijit** [comment]
@Swap76 please label it as hacktoberfest

**Comment by adavijit** [comment]
@Swap76  #82 sent PR
