### ISSUE TITLE
bind() function should be there

### ISSUE THREAD

**Issue by adavijit** [Swap76/Learn-JavaScript#85]

**Comment by Swap76** [comment]
@adavijit  Will ad this as an issue with the description as people won't open issues with comments thinking these are taken 

thanks for suggestions your suggestions are very valuable  

Also, I will be creating a common issue where you can tell me what else we can add and then we will on that

**Comment by Swap76** [comment]
@adavijit Created issue with the description for bind

Thanks looking forward to working with you
