### ISSUE TITLE
Add Bind Function of JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#86]
Create a new file named bind in JavaScript_Advance and add the following:

- Where we use Bind Function in .md 
- how we make Bind Function in .md
- Example of bind function in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by adavijit** [comment]
I want to go with it

**Comment by Swap76** [comment]
@adavijit Will assign the issue to you :-)

**Comment by adavijit** [comment]
@Swap76  done! sent PR
