### ISSUE TITLE
Suggest JavaScript concepts and add it that are not there

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#87]
This is a common issue where anyone can tell me about the concepts or examples they want to add 

After that 
- I will be creating a separate issue for that to keep track of the work
- Will assign to the person
- Start Contributing  :-)

Thanks to all for making this project so big :-)

**Comment by fcosueza** [comment]
Can i add Set object ? :)

**Comment by Swap76** [comment]
@fcosueza Created issue for you please comment at #91

**Comment by dkr19** [comment]
I want to add topic - 'Currying'.

**Comment by rishabhx64** [comment]
Can I add Coercion?

**Comment by Swap76** [comment]
@dkr19 I have created an issue for curring  #96  please comment there so that I can assign it to you :-)

**Comment by Swap76** [comment]
@rishabhx64 I have created an issue for coercion #97  please comment there so that I can assign it to you :-)

**Comment by Tamy123** [comment]
Can i add the Map Object?

**Comment by Swap76** [comment]
@Tamy123 I have created an issue for Map Object #102  please comment there so that I can assign it to you :-)

**Comment by Swap76** [comment]
@adavijit I have created #107 for concat ()

Just a doubt you want the rest-spread operator or something different as rest-spread is there in JavaScript Advance

**Comment by adavijit** [comment]
@Swap76 
Yes! I wrote about the rest-spread operator!

**Comment by Swap76** [comment]
@adavijit Please comment at #107
