### ISSUE TITLE
Add Set function 

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#91]
Create a new file named set-function in JavaScript_Advance and add the following:

- Where we use set-function in .md
- how we make set-function in .md
- Example of set-function in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by fcosueza** [comment]
Thanks, but i was talking about Set object, which is different from set() function.

**Comment by Swap76** [comment]
Cool :-)

**Comment by fcosueza** [comment]
Seems, like #92 and #93 fix this issue, then i'll add Set object, if cool :smiley:

**Comment by Swap76** [comment]
@fcosueza Created Set Object for you #95 Comment here to assign it to you

Sorry for the inconvenience caused.
