### ISSUE TITLE
Add Currying in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#96]
Create a new file named currying in JavaScript_Advance and add the following:

- Where we use currying in .md
- how we make currying in .md
- Example of currying in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by Tamy123** [comment]
Assign this to me as well?

**Comment by Swap76** [comment]
@Tamy123  
This issue is created on request by @dkr19 if he doesn’t work on this in 2 days you can take this

**Comment by Tamy123** [comment]
Ok im waiting

**Comment by Swap76** [comment]
@Tamy123 you can start working on this :-)

**Comment by Tamy123** [comment]
Sure bro but assign it to me first? :)

**Comment by Tamy123** [comment]
Thanks i ll do this today!

**Comment by cptcrunchy** [comment]
Will this cover partial application or just currying?

**Comment by Swap76** [comment]
@cptcrunchy Cool
