### ISSUE TITLE
Add Coercion in JavaScript

### ISSUE THREAD

**Issue by Swap76** [Swap76/Learn-JavaScript#97]
Create a new file named coercion in JavaScript_Advance and add the following:

- Where we use coercion in .md
- how we make coercion in .md
- Example of coercion in .js

Create .md and .js both files as we are shifting to Docsify

**Comment by RocktimSaikia** [comment]
@Swap76  I'll take it

**Comment by rishabhx64** [comment]
@Swap76 I'll start working on this issue right away.

**Comment by Swap76** [comment]
Hey @RocktimSaikia,
This issue is created especially for @rishabhx64 as he has asked for it in #87 

If you also want something specific that you can work on please let me know
